spring:
  # datasource Setting
  datasource:
    url: jdbc:h2:tcp://localhost/~/cardMap
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

# Logging Setting
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # query parameter ??